apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::811652874171:role/eksctl-eksctl-demo-nodegroup-ng-3-NodeInstanceRole-18U6QP5XXAJWP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::811652874171:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-13T10:55:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1645"
  uid: 5023c74e-17d4-4f03-a198-02a42d4bfaae
